# Generated by Django 4.0 on 2021-12-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_author_id_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
